### PR TITLE
set num_interested as upper bound for ak participants

### PR DESCRIPTION
**Pull request by Lorax66**
Improve on issue #3

### CODE REVIEW

**Review by felixblanke — APPROVED** [review]
LGTM.
Can you add the changes to the LP [to the Wiki entry](https://github.com/Die-KoMa/ak-plan-optimierung/wiki/New-LP-Formulation) once its merged?

**Comment by felixblanke** [comment]
I notice possible regressions on the test cases

**Comment by Lorax66** [comment]
What do you mean by regressions?

**Review by felixblanke — APPROVED** [review]
I noticed some some tests failing that according to my memory did not before (called a [regression](https://en.wikipedia.org/wiki/Software_regression)). However, this was due to some solvers not finding a valid solution in the allotted time, see #10

**Pull request merged**
